c_text = "TUQRQ AKJBO MDIYL GTEEU KTRKZ QDLLN BNUSV ICIXF UJISZ UYLGR QWTIO MPQKX QALIN TOHED CFMTE ALMBV GFTZI JMYFE FHGPK ZEOWB NZTET IGAVD ESHGP XAUYL GPKDE XSEUI XUTEA LGRFG VQMJM NWBPQ ZUNYX BXOOO XGBVB QRKEG QUZTG MGASQ MTIEA LDOEX UMIXU TMGAU ANYSG QTFOL LRXGB EJWGP XAUYL BCZQN YPNVJ FHWFB IYFEV XBCXA FLLRE UDLVA NAZML CIQIH AULHV AVGTW HNZMG EVAVB NMSEY PPCMR EXUIY UFLLR AANJW GGEKD ESRBB NQRSP NJGYA UPNQS EOEIG WUWSA HRACU TZTUQ RQAKJ BOMNU LXUMR MRYIZ IPARA XLANA OCXUM ODHWE QAGZD VIPTG DEVET IOZSL LVUOF WSWNJ YGRVM ZXUES AFYMZ TEQHR KRMRW HGPGF TZIGW ADOXX UMCAR DHPWA XDTIZ IJQEP GRXZF HWSEM ZUCSP YGGZD GRCIV QRARG POEMA RVUAY OXXVU KMNVA VBNFH WIKQY FIFKZ MGZSG JGZGH EDPVV M"

length = 7
offset = 0

text_list = list(c_text)

_list = []

for i in range(0, length):
    _list += [[]]

for i in range(0, len(text_list)):
    if text_list[i] != ' ' and text_list[i] != '\n':
        _list[offset] += [text_list[i]]
        offset = offset + 1
        offset = offset % 7

for i in _list:
    print(''.join(i))
